version: "3.9"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: workflow_ai
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile.local
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/workflow_ai
      GCS_BUCKET: ${GCS_BUCKET:-}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      CORS_ORIGINS: ${CORS_ORIGINS:-http://localhost:5173}
      PORT: "8000"
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app

volumes:
  pgdata: 